### ISSUE TITLE
How to increase speed of indeterminate progress animation and color

### ISSUE THREAD

**Issue by kashifandroiddev** [DreaminginCodeZH/MaterialProgressBar#11]
how to increase speed of animation and how to appy custom color 

it get colorAccent by default
but i want to chage it 

thanks

**Comment by zhanghai** [comment]
As mentioned in README, you can use `android:tint` for color other than `?colorAccent`.

But as for the speed of animation, you will need to manually modify [me/zhanghai/android/materialprogressbar/Animators.java](library/src/main/java/me/zhanghai/android/materialprogressbar/Animators.java) and change the arguments of `setDuration()`.

The `Animators` class is intended to be a java backport for framework XML animators, and since most people should follow the native progressbar behavior, no customizable interface is exposed.

**Comment by kashifandroiddev** [comment]
ok thanks for your help........
