### ISSUE TITLE
Integrate Proguard rules

### ISSUE THREAD

**Issue by zhanghai** [DreaminginCodeZH/MaterialProgressBar#4]
As in afollestad/material-dialogs#708.

**Comment by zhanghai** [comment]
Done.

**Comment by ashughes** [comment]
You should specify the `consumerProguardFiles` in `defaultConfig` rather than `buildTypes/release` so that it works if the consuming application proguards in both debug and release mode (e.g. to avoid the 65k dex method limit).

```
defaultConfig {
    consumerProguardFiles 'proguard-rules.txt'
}
```

I would also suggest removing `minifyEnabled false` from your library's `buildTypes/release` as this is something that should be specified by the consuming application.

**Comment by zhanghai** [comment]
Good point on dex method limit, I'll move the rules to defaultConfig now. Thank you.

**Comment by zhanghai** [comment]
Released.
