### ISSUE TITLE
Crashes while updating to 1.6.0 library version

### ISSUE THREAD

**Issue by milkaman** [DreaminginCodeZH/MaterialProgressBar#85]
There are some breaking changes, some methods are deprecated.
It would be great if next time you add some notes to README for example.

For example `setIndeterminateTintList(@Nullable ColorStateList tint)` is not deprecated and it will crash the app.

It will not take so much time, but lot's of users will be aware what to change and check in code.

Maybe I didn't found such file, but seems like it doesn't exist yet.

I really like your library and hope that next time I would know about breaking changes and deprecated methods before crashes on production :)

**Comment by zhanghai** [comment]
Sorry to hear that your app was crashing.

If you take a look at the changes between v1.4.2 and v1.6.0 on MaterialProgressBar.java, you may find that the changes was about moving setIndeterminateTintList() implementation into setSupportIndeterminateTintList(), which won't cause confusion when targetting API < 21 and using a framework ProgressBar typed variable, and should be the right thing to do. In order to keep compatible, I made setIndeterminateTintList() to just call setSupportIndeterminateTintList() and log an additional warning, which shouldn't be a breaking change.

But yes, it would be better if I added the deprecation notice to release notes, I'm sorry about that and I will do it in future releases. I missed this one mainly because it was done in Nov 2017 and intended to be release in v1.5.0 (which wasn't released), so I forgot it due to it being long time ago.

**Comment by milkaman** [comment]
Thanks for quick response)

I found the right method in a second, but just want that other users would be aware of that case.

**Comment by zhanghai** [comment]
I've updated the release notes to mention this; although I didn't expect this deprecation to actually break apps because it is made to call the same method just with an additional warning in logcat.
